version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      deepseek-dsh:
        patterns:
          - '@deepseek-ai/dsh*'
      language-servers:
        patterns:
          - pyright
          - typescript-language-server
          - vscode-langservers-extracted
          - yaml-language-server

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
